<a href="https://colab.research.google.com/github/muneer-ahmad10/Natural-Language-processing/blob/main/Day_13_mini_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import math

In [2]:
embeddings=nn.Embedding(3,4)

In [3]:
tokens=torch.tensor([0,1,2])

In [4]:
x=embeddings(tokens)

In [5]:
x.shape

torch.Size([3, 4])

In [6]:
x

tensor([[ 1.4053, -1.0579, -1.2416, -0.3483],
        [-0.8898, -1.2856, -1.9578,  0.2163],
        [-0.8779, -0.8154, -2.2485, -1.2978]], grad_fn=<EmbeddingBackward0>)

In [7]:
Wq=nn.Linear(4,4)
Wk=nn.Linear(4,4)
Wv=nn.Linear(4,4)

In [8]:
Wq

Linear(in_features=4, out_features=4, bias=True)

In [9]:
Wk

Linear(in_features=4, out_features=4, bias=True)

In [10]:
Q=Wq(x)
K=Wk(x)
V=Wv(x)

In [11]:
Q

tensor([[-0.2443,  1.3265, -1.7346, -0.1403],
        [ 0.8998,  2.1749, -1.0220, -0.9433],
        [ 1.6586,  1.3904, -1.5287, -1.2410]], grad_fn=<AddmmBackward0>)

In [12]:
K

tensor([[-0.3512,  0.9630, -0.8063, -0.2802],
        [ 1.2520,  1.4807, -1.6354,  0.9141],
        [ 0.5631,  2.1934, -2.2518,  1.6838]], grad_fn=<AddmmBackward0>)

In [13]:
V

tensor([[ 0.9634, -0.4891,  0.5096, -0.2301],
        [ 1.1398, -1.4128, -0.1084, -0.2700],
        [ 0.9969, -0.9550, -0.2723, -0.4313]], grad_fn=<AddmmBackward0>)

In [14]:
scores=Q @ K.T

In [15]:
scores=scores / math.sqrt(4)

In [16]:
weights=torch.softmax(
    scores,
    dim=-1
)

In [17]:
context=weights @ V

In [18]:
print(context)

tensor([[ 1.0267, -1.0123, -0.1505, -0.3721],
        [ 1.0436, -1.0642, -0.1267, -0.3519],
        [ 1.0609, -1.1253, -0.1196, -0.3360]], grad_fn=<MmBackward0>)


**Explain self-attention**

Self-attention allows each token to compare itself with every other token using Query and Key vectors. The resulting attention weights determine how much information to gather from the Value vectors, creating a context-aware representation of each word