<a href="https://colab.research.google.com/github/muneer-ahmad10/Natural-Language-processing/blob/main/Day_08_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn.functional as f

In [5]:
# Suppose sentence "I love NLP"

embeddings = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],  # I
    [0.0, 2.0, 0.0, 2.0],  # love
    [1.0, 1.0, 1.0, 1.0]   # NLP
])

In [7]:
embeddings.shape # 3 words 4 dim

torch.Size([3, 4])

In [12]:
#Q = K = V = embeddings

Q=embeddings
K=embeddings
V=embeddings

In [16]:
Q

tensor([[1., 0., 1., 0.],
        [0., 2., 0., 2.],
        [1., 1., 1., 1.]])

In [15]:
K.T

tensor([[1., 0., 1.],
        [0., 2., 1.],
        [1., 0., 1.],
        [0., 2., 1.]])

In [17]:
scores=torch.matmul(Q,K.T) # every word with every word

In [18]:
scores

tensor([[2., 0., 2.],
        [0., 8., 4.],
        [2., 4., 4.]])

In [20]:
#        # i. Love NLP
# tensor([[2., 0., 2.], #i
#         [0., 8., 4.], #Love
#         [2., 4., 4.]])#NLP

In [21]:

attention_weighs=f.softmax(scores,dim=1)

In [22]:
attention_weighs

tensor([[4.6831e-01, 6.3379e-02, 4.6831e-01],
        [3.2932e-04, 9.8169e-01, 1.7980e-02],
        [6.3379e-02, 4.6831e-01, 4.6831e-01]])

In [23]:
4.6831e-01 + 6.3379e-02 + 4.6831e-01

0.999999

In [24]:
3.2932e-04 + 9.8169e-01 + 1.7980e-02

0.9999993199999999

In [25]:
6.3379e-02 + 4.6831e-01 + 4.6831e-01

0.999999

In [26]:
# Softmax turns every raw value into probablities each row  sums to almost 1

In [28]:
output = torch.matmul(attention_weighs, V)

print(output)

tensor([[0.9366, 0.5951, 0.9366, 0.5951],
        [0.0183, 1.9814, 0.0183, 1.9814],
        [0.5317, 1.4049, 0.5317, 1.4049]])


In [29]:
# each word representation becomes combination of important words
# Example:
# NLP representation now contains information from "love"

In [31]:
# Word embeddings
embeddings = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],  # I
    [0.0, 2.0, 0.0, 2.0],  # love
    [1.0, 1.0, 1.0, 1.0]   # NLP
])

# Q K V
Q = embeddings
K = embeddings
V = embeddings

# Similarity scores
scores = torch.matmul(Q, K.T)

# Attention weights
attention_weights = f.softmax(scores, dim=1)

# Final output
output = torch.matmul(attention_weights, V)

print("Scores:\n", scores)
print("\nAttention Weights:\n", attention_weights)
print("\nFinal Output:\n", output)

Scores:
 tensor([[2., 0., 2.],
        [0., 8., 4.],
        [2., 4., 4.]])

Attention Weights:
 tensor([[4.6831e-01, 6.3379e-02, 4.6831e-01],
        [3.2932e-04, 9.8169e-01, 1.7980e-02],
        [6.3379e-02, 4.6831e-01, 4.6831e-01]])

Final Output:
 tensor([[0.9366, 0.5951, 0.9366, 0.5951],
        [0.0183, 1.9814, 0.0183, 1.9814],
        [0.5317, 1.4049, 0.5317, 1.4049]])


# **Scaled Dot Product Attention**

In [33]:
# when the vectors become large dot product becomes huge e.g vectors are 100,200,500 softmax becomes extreme for 500 softmax will be 0.999999 and dor 100 it will be 0.00001 this means model become more confident and training becomes unstable


# to solve this problem we scale scores down and here transformer paper introduced. Attention
# (𝑄,𝐾,𝑉)=softmax(𝑄𝐾.𝑇 / sqrt(𝑑𝑘))𝑉

# dk the dimension of key vectors which is taken out using K.shape[-1] we perform sq.root to it and divide it to the scores .scores=𝑄𝐾.𝑇

In [36]:
embeddings = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],  # I
    [0.0, 2.0, 0.0, 2.0],  # love
    [1.0, 1.0, 1.0, 1.0]   # NLP
])

# Q K V
Q = embeddings
K = embeddings
V = embeddings

# Similarity scores
scores = torch.matmul(Q, K.T)

#Scaling
dk=K.shape[-1]
scaled_scores=scores / torch.sqrt(torch.tensor(dk,dtype=torch.float32))

# Attention weights

attention_weights = f.softmax(scaled_scores, dim=1)

# Final output
output = torch.matmul(attention_weights, V)

output = torch.matmul(attention_weights, V)

print("Scores:\n", scores)

print("\nScaled Scores:\n", scaled_scores)

print("\nAttention Weights:\n", attention_weights)

print("\nFinal Output:\n", output)

Scores:
 tensor([[2., 0., 2.],
        [0., 8., 4.],
        [2., 4., 4.]])

Scaled Scores:
 tensor([[1., 0., 1.],
        [0., 4., 2.],
        [1., 2., 2.]])

Attention Weights:
 tensor([[0.4223, 0.1554, 0.4223],
        [0.0159, 0.8668, 0.1173],
        [0.1554, 0.4223, 0.4223]])

Final Output:
 tensor([[0.8446, 0.7330, 0.8446, 0.7330],
        [0.1332, 1.8509, 0.1332, 1.8509],
        [0.5777, 1.2670, 0.5777, 1.2670]])


In [35]:
# if embedding dimension increases scores become very large scaling prevents softmax saturation